Bug 59260: clean up shell scripts with ShellCheck

diff --git a/bin.dist/processApproved b/bin.dist/processApproved
--- a/bin.dist/processApproved
+++ b/bin.dist/processApproved
@@ -19,11 +19,11 @@
 
 NEWSBIN=/var/lib/newsbin; export NEWSBIN
 shift
-DATE_STAMP="`date +%y%m%d%H%M%S`"
+DATE_STAMP="$(date +%y%m%d%H%M%S)"
 
-TMPFILE=$TMP/pa.$DATE_STAMP.$$
+TMPFILE="$TMP"/pa."$DATE_STAMP".$$
 
-if [ $PGP = "none" ]; then
+if [ "$PGP" = "none" ]; then
   PMAPP_PROG=cat
 else
   PMAPP_PROG="PMAPP $NEWSGROUP"
@@ -31,27 +31,26 @@ fi
 
 echo Action: processApproved 1>&2
 
-cat > $TMPFILE
+cat > "$TMPFILE"
 
 save() { 
 
   ( 
-    cat $TMPFILE
-  ) | procmail -f- $MNG_ROOT/etc/procmail/save-approved
+    cat "$TMPFILE"
+  ) | procmail -f- "$MNG_ROOT"/etc/procmail/save-approved
 }
 
 post() {
-  FAILED=$TMP/failed.$$
+  FAILED="$TMP"/failed.$$
   (
     echo Path: "$PATH_SUFFIX"
 
-    cat $MNG_ROOT/etc/added-headers | grep ': ' 
+    grep ': ' < "$MNG_ROOT"/etc/added-headers
     # I do grep above because a lot of users inserts empty
     # lines in the added headers.
 
-    echo Date: `date "+%a, %e %b %Y %H:%M:%S CST"`
-    cat $TMPFILE					\
-      | formail -f -a "Newsgroups: $NEWSGROUP"		\
+    echo Date: "$(date "+%a, %e %b %Y %H:%M:%S CST")"
+    formail -f -a "Newsgroups: $NEWSGROUP"		\
 	    -I Path:					\
             -I X-Moderate-For:                          \
             -I Return-Path:                             \
@@ -62,20 +61,21 @@ post() {
 	    -a "Approved: $PMUSER_APPROVAL"		\
             -I Lines:                                   \
             -I Cc:                                      \
-	    -I To: -I Status:
+	    -I To: -I Status:                           \
+	    < "$TMPFILE"
 
-    if [ -f $MNG_ROOT/etc/added-footer ] ; then
-      cat $MNG_ROOT/etc/added-footer
+    if [ -f "$MNG_ROOT"/etc/added-footer ] ; then
+      cat "$MNG_ROOT"/etc/added-footer
     fi
 
   )                                                     \
-    | $PMAPP_PROG					\
-    | tee $FAILED                                       \
-    | $RNEWS
+    | "$PMAPP_PROG"					\
+    | tee "$FAILED"                                     \
+    | "$RNEWS"
   if [ "$?" = "0" ] ; then
-    /bin/rm $FAILED
+    /bin/rm "$FAILED"
   else
-    echo IHAVE failed. Look at $FAILED. 1>&2
+    echo IHAVE failed. Look at "$FAILED". 1>&2
   fi
 }
 
@@ -84,8 +84,8 @@ ROBOMOD="$ROBOMOD_APPROVAL"; export ROBOMOD
 save
 post
 
-if needAck < $TMPFILE; then
-  modack.approved $TMPFILE
+if needAck < "$TMPFILE"; then
+  modack.approved "$TMPFILE"
 fi
 
-rm $TMPFILE
+rm "$TMPFILE"
